# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraints.xdc

# Block Designs: bd/IRIS_Block_Design/IRIS_Block_Design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==IRIS_Block_Design || ORIG_REF_NAME==IRIS_Block_Design} -quiet] -quiet

# IP: bd/IRIS_Block_Design/ip/IRIS_Block_Design_microblaze_0_0/IRIS_Block_Design_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==IRIS_Block_Design_microblaze_0_0 || ORIG_REF_NAME==IRIS_Block_Design_microblaze_0_0} -quiet] -quiet

# IP: bd/IRIS_Block_Design/ip/IRIS_Block_Design_clk_wiz_0_0/IRIS_Block_Design_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==IRIS_Block_Design_clk_wiz_0_0 || ORIG_REF_NAME==IRIS_Block_Design_clk_wiz_0_0} -quiet] -quiet

# IP: bd/IRIS_Block_Design/ip/IRIS_Block_Design_axi_uartlite_0_0/IRIS_Block_Design_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==IRIS_Block_Design_axi_uartlite_0_0 || ORIG_REF_NAME==IRIS_Block_Design_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/IRIS_Block_Design/ip/IRIS_Block_Design_dlmb_v10_0/IRIS_Block_Design_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==IRIS_Block_Design_dlmb_v10_0 || ORIG_REF_NAME==IRIS_Block_Design_dlmb_v10_0} -quiet] -quiet

# IP: bd/IRIS_Block_Design/ip/IRIS_Block_Design_ilmb_v10_0/IRIS_Block_Design_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==IRIS_Block_Design_ilmb_v10_0 || ORIG_REF_NAME==IRIS_Block_Design_ilmb_v10_0} -quiet] -quiet

# IP: bd/IRIS_Block_Design/ip/IRIS_Block_Design_dlmb_bram_if_cntlr_0/IRIS_Block_Design_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==IRIS_Block_Design_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==IRIS_Block_Design_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/IRIS_Block_Design/ip/IRIS_Block_Design_ilmb_bram_if_cntlr_0/IRIS_Block_Design_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==IRIS_Block_Design_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==IRIS_Block_Design_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/IRIS_Block_Design/ip/IRIS_Block_Design_lmb_bram_0/IRIS_Block_Design_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==IRIS_Block_Design_lmb_bram_0 || ORIG_REF_NAME==IRIS_Block_Design_lmb_bram_0} -quiet] -quiet

# IP: bd/IRIS_Block_Design/ip/IRIS_Block_Design_mdm_1_0/IRIS_Block_Design_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==IRIS_Block_Design_mdm_1_0 || ORIG_REF_NAME==IRIS_Block_Design_mdm_1_0} -quiet] -quiet

# IP: bd/IRIS_Block_Design/ip/IRIS_Block_Design_rst_clk_wiz_0_100M_0/IRIS_Block_Design_rst_clk_wiz_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==IRIS_Block_Design_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==IRIS_Block_Design_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/IRIS_Block_Design/ip/IRIS_Block_Design_xbar_0/IRIS_Block_Design_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==IRIS_Block_Design_xbar_0 || ORIG_REF_NAME==IRIS_Block_Design_xbar_0} -quiet] -quiet

# IP: bd/IRIS_Block_Design/ip/IRIS_Block_Design_microblaze_0_axi_periph_0/IRIS_Block_Design_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==IRIS_Block_Design_microblaze_0_axi_periph_0 || ORIG_REF_NAME==IRIS_Block_Design_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/IRIS_Block_Design/ip/IRIS_Block_Design_axi_gpio_0_0/IRIS_Block_Design_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==IRIS_Block_Design_axi_gpio_0_0 || ORIG_REF_NAME==IRIS_Block_Design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/IRIS_Block_Design/ip/IRIS_Block_Design_axi_gpio_1_0/IRIS_Block_Design_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==IRIS_Block_Design_axi_gpio_1_0 || ORIG_REF_NAME==IRIS_Block_Design_axi_gpio_1_0} -quiet] -quiet

# XDC: c:/Users/yohan/Documents/IRIS_CubeSat/I.R.I.S. - CubeSat - Master.gen/sources_1/bd/IRIS_Block_Design/IRIS_Block_Design_ooc.xdc
