#include "xmicroblaze.h"

XMicroblaze_Config XMicroblaze_ConfigTable[] __attribute__ ((section (".drvcfg_sec"))) = {
	{
		0x0,  /* xlnx,unaligned-exceptions */
		 0,  /* xlnx,iopb-bus-exception */
		0x0,  /* xlnx,fpu-exception */
		0x0,  /* xlnx,fsl-exception */
		0x0,  /* xlnx,div-zero-exception */
		 0,  /* xlnx,dopb-bus-exception */
		0x0,  /* xlnx,ill-opcode-exception */
		0x0,  /* xlnx,use-stack-protection */
		 0,  /* xlnx,exceptions-in-delay-slots */
		 0,  /* xlnx,predecode-fpu-exception */
		0x5f5e100,  /* xlnx,freq */
		0x0,  /* xlnx,use-msr-instr */
		0x10,  /* d-cache-line-size */
		0x1,  /* xlnx,dcache-always-used */
		0x2000,  /* d-cache-size */
		0x10,  /* i-cache-line-size */
		0x2000,  /* i-cache-size */
		0x0,  /* xlnx,addr-tag-bits */
		0x1,  /* xlnx,allow-dcache-wr */
		0x1,  /* xlnx,allow-icache-wr */
		0x0,  /* xlnx,area-optimized */
		0x2000,  /* xlnx,cache-byte-size */
		0x1,  /* xlnx,d-lmb */
		 0,  /* xlnx,d-opb */
		 0,  /* xlnx,d-plb */
		0x1,  /* xlnx,i-lmb */
		 0,  /* xlnx,i-opb */
		 0,  /* xlnx,i-plb */
		0x0,  /* xlnx,dcache-addr-tag */
		0x2000,  /* xlnx,dcache-byte-size */
		0x4,  /* xlnx,dcache-line-len */
		 0,  /* xlnx,dcache-use-fsl */
		0x0,  /* xlnx,dcache-use-writeback */
		0x1,  /* xlnx,debug-enabled */
		0x0,  /* xlnx,dynamic-bus-sizing */
		0x1,  /* xlnx,edge-is-positive */
		0x5f5e100,  /* timebase-frequency */
		0x1,  /* xlnx,endianness */
		 0,  /* xlnx,fsl-data-size */
		0x0,  /* xlnx,fsl-links */
		0x1,  /* xlnx,icache-always-used */
		0x4,  /* xlnx,icache-line-len */
		 0,  /* xlnx,icache-use-fsl */
		0x2,  /* xlnx,interconnect */
		0x0,  /* xlnx,interrupt-is-edge */
		0x4,  /* xlnx,mmu-dtlb-size */
		0x2,  /* xlnx,mmu-itlb-size */
		0x3,  /* xlnx,mmu-tlb-access */
		0x10,  /* xlnx,mmu-zones */
		0x1,  /* xlnx,number-of-pc-brk */
		0x0,  /* xlnx,number-of-rd-addr-brk */
		0x0,  /* xlnx,number-of-wr-addr-brk */
		0x0,  /* xlnx,opcode-0x0-illegal */
		0x0,  /* xlnx,pvr */
		 0,  /* xlnx,pvr-user1 */
		0x0,  /* xlnx,pvr-user2 */
		0x0,  /* xlnx,reset-msr */
		0x0,  /* xlnx,sco */
		0x0,  /* xlnx,use-barrel */
		0x0,  /* xlnx,use-dcache */
		0x0,  /* xlnx,use-div */
		0x0,  /* xlnx,use-ext-brk */
		0x0,  /* xlnx,use-ext-nm-brk */
		0x0,  /* xlnx,use-extended-fsl-instr */
		0x0,  /* xlnx,use-fpu */
		0x0,  /* xlnx,use-hw-mul */
		0x0,  /* xlnx,use-icache */
		0x0,  /* xlnx,use-interrupt */
		0x0,  /* xlnx,use-mmu */
		0x0,  /* xlnx,use-pcmp-instr */
		0x0,  /* d-cache-baseaddr */
		0x3fffffff,  /* d-cache-highaddr */
		0x0,  /* i-cache-baseaddr */
		0x3fffffff,  /* i-cache-highaddr */
		 0,  /* microblaze_ddr_reserve_sa */
		 0,  /* microblaze_ddr_reserve_ea */
		0x0,  /* reg */
		0x0,
		0x0  /* xlnx,base-vectors */
	}
};