# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/yohan/Desktop/gtp_5g_test/gtp_5g_test.runs/synth_1/top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/yohan/Desktop/gtp_5g_test/gtp_5g_test.cache/wt [current_project]
set_property parent.project_path C:/Users/yohan/Desktop/gtp_5g_test/gtp_5g_test.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/yohan/Desktop/gtp_5g_test/gtp_5g_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_mem {
  C:/Users/yohan/Desktop/gtp_5g_test/gtp_5g_test.srcs/sources_1/imports/example_design/gt_rom_init_rx.dat
  C:/Users/yohan/Desktop/gtp_5g_test/gtp_5g_test.srcs/sources_1/imports/example_design/gt_rom_init_tx.dat
}
read_verilog -library xil_defaultlib {
  C:/Users/yohan/Desktop/gtp_5g_test/gtp_5g_test.srcs/sources_1/imports/example_design/support/gtp_clock_module.v
  C:/Users/yohan/Desktop/gtp_5g_test/gtp_5g_test.srcs/sources_1/imports/example_design/support/gtp_common.v
  C:/Users/yohan/Desktop/gtp_5g_test/gtp_5g_test.srcs/sources_1/imports/example_design/support/gtp_common_reset.v
  C:/Users/yohan/Desktop/gtp_5g_test/gtp_5g_test.srcs/sources_1/imports/example_design/support/gtp_cpll_railing.v
  C:/Users/yohan/Desktop/gtp_5g_test/gtp_5g_test.srcs/sources_1/imports/example_design/gtp_exdes.v
  C:/Users/yohan/Desktop/gtp_5g_test/gtp_5g_test.srcs/sources_1/imports/example_design/support/gtp_gt_usrclk_source.v
  C:/Users/yohan/Desktop/gtp_5g_test/gtp_5g_test.srcs/sources_1/imports/example_design/support/gtp_support.v
  C:/Users/yohan/Desktop/gtp_5g_test/gtp_5g_test.srcs/sources_1/packet_rec.v
  C:/Users/yohan/Desktop/gtp_5g_test/gtp_5g_test.srcs/sources_1/packet_send.v
  C:/Users/yohan/Desktop/gtp_5g_test/gtp_5g_test.srcs/sources_1/word_align.v
  C:/Users/yohan/Desktop/gtp_5g_test/gtp_5g_test.srcs/sources_1/new/top.v
}
read_ip -quiet c:/Users/yohan/Desktop/gtp_5g_test/gtp_5g_test.srcs/sources_1/ip/sys_clock/sys_clock.xci
set_property used_in_implementation false [get_files -all c:/Users/yohan/Desktop/gtp_5g_test/gtp_5g_test.gen/sources_1/ip/sys_clock/sys_clock_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yohan/Desktop/gtp_5g_test/gtp_5g_test.gen/sources_1/ip/sys_clock/sys_clock.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yohan/Desktop/gtp_5g_test/gtp_5g_test.gen/sources_1/ip/sys_clock/sys_clock_ooc.xdc]

read_ip -quiet c:/Users/yohan/Desktop/gtp_5g_test/gtp_5g_test.srcs/sources_1/ip/gtp/gtp.xci
set_property used_in_implementation false [get_files -all c:/Users/yohan/Desktop/gtp_5g_test/gtp_5g_test.gen/sources_1/ip/gtp/gtp.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yohan/Desktop/gtp_5g_test/gtp_5g_test.gen/sources_1/ip/gtp/gtp_ooc.xdc]

read_ip -quiet c:/Users/yohan/Desktop/gtp_5g_test/gtp_5g_test.srcs/sources_1/ip/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all c:/Users/yohan/Desktop/gtp_5g_test/gtp_5g_test.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yohan/Desktop/gtp_5g_test/gtp_5g_test.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yohan/Desktop/gtp_5g_test/gtp_5g_test.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yohan/Desktop/gtp_5g_test/gtp_5g_test.gen/sources_1/ip/ila_0/ila_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/yohan/Desktop/gtp_5g_test/gtp_5g_test.srcs/constrs_1/imports/example_design/gtp_exdes.xdc
set_property used_in_implementation false [get_files C:/Users/yohan/Desktop/gtp_5g_test/gtp_5g_test.srcs/constrs_1/imports/example_design/gtp_exdes.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top -part xc7a100tfgg484-2
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
