# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/yohan/Desktop/gtp_5g_test/gtp_5g_test.srcs/sources_1/ip/gtp/gtp.xci
# IP: The module: 'gtp' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yohan/Desktop/gtp_5g_test/gtp_5g_test.gen/sources_1/ip/gtp/gtp.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtp'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/yohan/Desktop/gtp_5g_test/gtp_5g_test.gen/sources_1/ip/gtp/gtp_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtp'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/yohan/Desktop/gtp_5g_test/gtp_5g_test.srcs/sources_1/ip/gtp/gtp.xci
# IP: The module: 'gtp' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yohan/Desktop/gtp_5g_test/gtp_5g_test.gen/sources_1/ip/gtp/gtp.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtp'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/yohan/Desktop/gtp_5g_test/gtp_5g_test.gen/sources_1/ip/gtp/gtp_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtp'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
