# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/yohan/Documents/IRIS_CubeSat/I.R.I.S. - CubeSat - Master.srcs/sources_1/bd/IRIS_Block_Design/ip/IRIS_Block_Design_axi_gpio_6_0/IRIS_Block_Design_axi_gpio_6_0.xci
# IP: The module: 'IRIS_Block_Design_axi_gpio_6_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yohan/Documents/IRIS_CubeSat/I.R.I.S. - CubeSat - Master.gen/sources_1/bd/IRIS_Block_Design/ip/IRIS_Block_Design_axi_gpio_6_0/IRIS_Block_Design_axi_gpio_6_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'IRIS_Block_Design_axi_gpio_6_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/yohan/Documents/IRIS_CubeSat/I.R.I.S. - CubeSat - Master.gen/sources_1/bd/IRIS_Block_Design/ip/IRIS_Block_Design_axi_gpio_6_0/IRIS_Block_Design_axi_gpio_6_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IRIS_Block_Design_axi_gpio_6_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/yohan/Documents/IRIS_CubeSat/I.R.I.S. - CubeSat - Master.gen/sources_1/bd/IRIS_Block_Design/ip/IRIS_Block_Design_axi_gpio_6_0/IRIS_Block_Design_axi_gpio_6_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'IRIS_Block_Design_axi_gpio_6_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/yohan/Documents/IRIS_CubeSat/I.R.I.S. - CubeSat - Master.srcs/sources_1/bd/IRIS_Block_Design/ip/IRIS_Block_Design_axi_gpio_6_0/IRIS_Block_Design_axi_gpio_6_0.xci
# IP: The module: 'IRIS_Block_Design_axi_gpio_6_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yohan/Documents/IRIS_CubeSat/I.R.I.S. - CubeSat - Master.gen/sources_1/bd/IRIS_Block_Design/ip/IRIS_Block_Design_axi_gpio_6_0/IRIS_Block_Design_axi_gpio_6_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'IRIS_Block_Design_axi_gpio_6_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/yohan/Documents/IRIS_CubeSat/I.R.I.S. - CubeSat - Master.gen/sources_1/bd/IRIS_Block_Design/ip/IRIS_Block_Design_axi_gpio_6_0/IRIS_Block_Design_axi_gpio_6_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IRIS_Block_Design_axi_gpio_6_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/yohan/Documents/IRIS_CubeSat/I.R.I.S. - CubeSat - Master.gen/sources_1/bd/IRIS_Block_Design/ip/IRIS_Block_Design_axi_gpio_6_0/IRIS_Block_Design_axi_gpio_6_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'IRIS_Block_Design_axi_gpio_6_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
